Repository GluuFederation/oxTrust, pull requests merged in 2018-08, with the labels that each got.

#1057 Validated contact list #1051
  server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java
Labels: enhancement

#1063 Add search box to attribute inventory #1061
  server/src/main/java/org/gluu/oxtrust/action/AttributeInventoryAction.java
  server/src/main/webapp/attribute/attributeInventory.xhtml
Labels: enhancement

#1065 Fix multivalue field issue #1060
  server/src/main/webapp/WEB-INF/incl/attribute/attributeForm.xhtml
Labels: bug, enhancement

#1085 Fix repeating search pattern issue #1081
  server/src/main/java/org/gluu/oxtrust/action/SearchClientAction.java
  server/src/main/java/org/gluu/oxtrust/action/SearchGroupAction.java
  server/src/main/java/org/gluu/oxtrust/action/SearchPersonAction.java
  server/src/main/java/org/gluu/oxtrust/action/SearchScopeAction.java
  server/src/main/java/org/gluu/oxtrust/action/SearchSectorIdentifierAction.java
  server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java
Labels: enhancement

#1084 Fix expiration date component #1080
  server/src/main/webapp/WEB-INF/incl/client/clientForm.xhtml
Labels: bug

#1086 Fix typo #1078
  server/src/main/webapp/WEB-INF/incl/attribute/attributeImportForm.xhtml
Labels: enhancement

#1087 Fix type in cache refresh section #1068
  server/src/main/resources/oxtrust.properties
  server/src/main/resources/oxtrust_en.properties
  server/src/main/resources/oxtrust_fr.properties
Labels: enhancement

#1089 #1088 save the smtpConfiguration
  server/src/main/java/org/gluu/oxtrust/action/UpdateOrganizationAction.java
Labels: bug

#1094 Audit log for oxtrust action #1041
  server/src/main/java/org/gluu/oxtrust/ldap/service/ApplianceService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/AsimbaService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/AttributeService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/AuthOrganizationService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/CentralLdapService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/ClientService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/EncryptionService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/FederationService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/FidoDeviceService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/FilterService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/GroupService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/IdGenService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/JsonConfigurationService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/LdifService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/MemberService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/OrganizationService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/OxTrustAuditService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/PassportService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/PersonService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/ScopeService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/SectorIdentifierService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/TrustService.java
  server/src/main/resources/log4j2.xml
  server/src/test/java/org/gluu/oxtrust/service/test/ApplianceStatusTest.java
Labels: enhancement

#1095 Fix mail validation #1090
  server/src/main/webapp/WEB-INF/incl/organization/organizationForm.xhtml
Labels: enhancement

#1098 #1091 remove buildDate and buildNumber from organization oxTrustSettings
  server/src/main/java/org/gluu/oxtrust/action/UpdateOrganizationAction.java
  server/src/main/webapp/WEB-INF/incl/organization/organizationForm.xhtml
Labels: bug

#1102 #1092 fix typo
  server/src/main/java/org/gluu/oxtrust/action/ConfigureCacheRefreshAction.java
Labels: bug

#1104 Ox trust/issues/1090
  server/src/main/webapp/WEB-INF/incl/organization/organizationForm.xhtml
Labels: enhancement

#1105 Ox trust/issues/1064
  server/src/main/webapp-jetty/WEB-INF/web.xml
Labels: bug, enhancement

#1107 #1082 encode the client secret
  server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java
  server/src/main/java/org/gluu/oxtrust/ldap/cache/service/CacheRefreshTimer.java
Labels: bug

#1108 Fix gender field #1099
  server/src/main/webapp/profile/person/viewProfile.xhtml
Labels: enhancement

#1110 Fix user add bug #1109
  server/src/main/java/org/gluu/oxtrust/action/UpdatePersonAction.java
Labels: bug

#1111 Ox trust/issues/1041
  server/src/main/java/org/gluu/oxtrust/action/Authenticator.java
  server/src/main/java/org/gluu/oxtrust/action/PasswordReminderAction.java
  server/src/main/java/org/gluu/oxtrust/action/PasswordResetAction.java
  server/src/main/java/org/gluu/oxtrust/action/PersonImportAction.java
  server/src/main/java/org/gluu/oxtrust/action/RegisterPersonAction.java
  server/src/main/java/org/gluu/oxtrust/action/UpdateAttributeAction.java
  server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java
  server/src/main/java/org/gluu/oxtrust/action/UpdateGroupAction.java
  server/src/main/java/org/gluu/oxtrust/action/UpdatePersonAction.java
  server/src/main/java/org/gluu/oxtrust/action/UpdateScopeAction.java
  server/src/main/java/org/gluu/oxtrust/action/UpdateSectorIdentifierAction.java
  server/src/main/java/org/gluu/oxtrust/action/UpdateTrustRelationshipAction.java
  server/src/main/java/org/gluu/oxtrust/action/UserProfileAction.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/ApplianceService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/AttributeService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/AuthOrganizationService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/CentralLdapService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/ClientService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/FidoDeviceService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/GroupService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/MemberService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/OxTrustAuditService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/PassportService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/PersonService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/ScopeService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/SectorIdentifierService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/TrustService.java
  server/src/main/resources/log4j2.xml
Labels: enhancement

#1124 #1122 use description of SimpleCustomProperty as placeholder
  server/src/main/java/org/gluu/oxtrust/action/ManagePersonAuthenticationAction.java
  server/src/main/webapp/resources/ox/simpleCustomPropertiesList.xhtml
Labels: enhancement

#1125 Fix mail validation #1115
  server/src/main/webapp/WEB-INF/incl/person/personForm.xhtml
Labels: enhancement

#1113 #1106 use SecureRandom to generate passwords
  server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java
  server/src/main/java/org/gluu/oxtrust/service/PasswordGenerator.java
  server/src/test/java/org/gluu/oxtrust/service/PasswordGeneratorTest.java
Labels: enhancement

#1123 Ox trust/issues/1117
  server/src/main/java/org/gluu/oxtrust/action/PasswordValidationAction.java
  server/src/main/webapp/person/updatePerson.xhtml
Labels: bug

#1127 Fix cache refresh issue #1120
  server/profiles/default/config-build.properties
  server/src/main/java/org/gluu/oxtrust/action/ConfigureCacheRefreshAction.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/OxTrustAuditService.java
  server/src/main/webapp/resources/ox/simplePropertiesList.xhtml
Labels: bug

#1128 Fix client sector uri bug/enhacement #966
  server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java
Labels: bug, enhancement

#1130 Fix typo #1129
  server/src/main/webapp/logviewer/configureLogViewer.xhtml
Labels: enhancement

#1136 Fix missing import
  server/src/main/java/org/gluu/oxtrust/action/PasswordValidationAction.java
Labels: bug

#1133 Fix search typo #1131
  server/src/main/java/org/gluu/oxtrust/action/SearchPersonAction.java
Labels: bug

#1142 Fix some issues #oxTrust/issues/1138
  server/src/main/java/org/gluu/oxtrust/action/UpdatePersonAction.java
  server/src/main/java/org/gluu/oxtrust/action/UserProfileAction.java
  server/src/main/webapp/WEB-INF/incl/attribute/attributeForm.xhtml
  server/src/main/webapp/WEB-INF/incl/layout/fullWidthEmpty.xhtml
  server/src/main/webapp/WEB-INF/incl/layout/newtemplate.xhtml
  server/src/main/webapp/register.xhtml
Labels: bug, enhancement

#1154 Fix custom attribute level issue #1143
  server/pom.xml
  server/src/main/webapp/WEB-INF/incl/script/customScriptListForm.xhtml
  server/src/main/webapp/resources/ox/simpleCustomPropertiesList.xhtml
Labels: bug, enhancement

#1155 Enhacement audit log #1146
  server/src/main/java/org/gluu/oxtrust/action/PasswordValidationAction.java
  server/src/main/java/org/gluu/oxtrust/action/RegisterPersonAction.java
  server/src/main/java/org/gluu/oxtrust/action/UpdateAttributeAction.java
  server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java
  server/src/main/java/org/gluu/oxtrust/action/UpdateGroupAction.java
  server/src/main/java/org/gluu/oxtrust/action/UpdatePersonAction.java
  server/src/main/java/org/gluu/oxtrust/action/UpdateScopeAction.java
  server/src/main/java/org/gluu/oxtrust/action/UpdateTrustRelationshipAction.java
  server/src/main/java/org/gluu/oxtrust/action/UserProfileAction.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/OxTrustAuditService.java
  server/src/main/resources/log4j2.xml
Labels: enhancement

#1159 Fix cache refresh mapping #1157
  server/src/main/webapp/resources/ox/simpleCustomPropertiesList.xhtml
Labels: bug, enhancement

#1160 Fix ldap server remove button #1158
  server/src/main/webapp/resources/ox/ldapConfig.xhtml
Labels: enhancement

#1165 Review max file upload size #1148
  server/src/main/webapp-jetty/WEB-INF/web.xml
Labels: enhancement

#1166 Enhance password reset message content and format #1151
  server/src/main/resources/oxtrust_en.properties
Labels: enhancement

#1167 Enhance some views #1152
  server/src/main/java/org/gluu/oxtrust/action/PasswordReminderAction.java
  server/src/main/java/org/gluu/oxtrust/action/PasswordResetAction.java
  server/src/main/webapp/person/passwordReminder.xhtml
  server/src/main/webapp/register.xhtml
  server/src/main/webapp/resetPassword.xhtml
Labels: enhancement
