Repository GluuFederation/oxTrust, pull requests merged in 2018-12, with the labels that each got.

#1379 Oxtrust Admin Ui Client is delete from Clients list few hour after in…
  server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java
  server/src/main/java/org/gluu/oxtrust/model/OxAuthClient.java
Labels: High Priority

#1346 Ox trust/issues/#1341
  server/src/main/java/org/gluu/oxtrust/api/attributes/AttributeWebResource.java
  server/src/main/java/org/gluu/oxtrust/api/certificates/CertificatesWebService.java
  server/src/main/java/org/gluu/oxtrust/api/client/ClientWebService.java
  server/src/main/java/org/gluu/oxtrust/api/log/LogsWebService.java
  server/src/main/java/org/gluu/oxtrust/api/openidconnect/ClientWebResource.java
  server/src/main/java/org/gluu/oxtrust/api/openidconnect/ScopeWebResource.java
  server/src/main/java/org/gluu/oxtrust/api/openidconnect/SectorIdentifierWebResource.java
  server/src/main/java/org/gluu/oxtrust/api/openidconnect/ServerStatusWebResource.java
  server/src/main/java/org/gluu/oxtrust/api/organization/OrganizationImageDTO.java
  server/src/main/java/org/gluu/oxtrust/api/organization/OrganizationImageResource.java
  server/src/main/java/org/gluu/oxtrust/api/organization/OrganizationResource.java
  server/src/main/java/org/gluu/oxtrust/api/organization/SmtpResource.java
  server/src/main/java/org/gluu/oxtrust/api/oxauth/OxAuthConfigurationWebService.java
  server/src/main/java/org/gluu/oxtrust/api/oxtrust/OxTrustConfigurationWebService.java
  server/src/main/java/org/gluu/oxtrust/api/rest/InumDTO.java
  server/src/main/java/org/gluu/oxtrust/api/rest/InumRestWebServiceV2.java
  server/src/main/java/org/gluu/oxtrust/api/saml/TrustRelationshipWebService.java
  server/src/main/java/org/gluu/oxtrust/api/uma/UmaResourceWebResource.java
  server/src/main/java/org/gluu/oxtrust/api/uma/UmaScopeWebResource.java
  server/src/main/java/org/gluu/oxtrust/api/users/GroupWebResource.java
  server/src/main/java/org/gluu/oxtrust/api/users/PeopleWebResource.java
Labels: enhancement

#1383 Add a way to list/delete users pairIdentifiers #1382
  server/src/main/java/org/gluu/oxtrust/action/UpdatePersonAction.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/IPairwiseIdService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/PairwiseIdService.java
  server/src/main/java/org/gluu/oxtrust/model/GluuUserPairwiseIdentifier.java
  server/src/main/webapp/WEB-INF/incl/person/personForm.xhtml
Labels: enhancement

#1388 Errors with User addition/edition #1386
  server/src/main/java/org/gluu/oxtrust/ldap/service/PairwiseIdService.java
Labels: bug

#1390 oopw while view Oxtrust Admin client details #1389
  server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java
Labels: bug

#1391 Remove Visibility type from Type dropdown in Add Group #1384
  server/src/main/webapp/WEB-INF/incl/group/groupForm.xhtml
Labels: bug

#1392 Remove Select from Allow for dynamic registration dropdown in Add Sco…
  server/src/main/webapp/WEB-INF/incl/scope/scopeForm.xhtml
Labels: bug

#1394 NPE when checking Certificates management view #1393
  server/src/main/java/org/gluu/oxtrust/action/CertificateManagementAction.java
Labels: bug

#1397 Some error related to recaptcha. #1395
  server/src/main/java/org/gluu/oxtrust/action/PasswordResetAction.java
  server/src/main/java/org/gluu/oxtrust/util/RecaptchaUtil.java
Labels: bug

#1398 improper log level for some log lines #1396
  server/src/main/java/org/gluu/oxtrust/ldap/service/AttributeService.java
Labels: enhancement

#1399 Improve OpenID Scope selection UX #1292
  server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java
  server/src/main/java/org/gluu/oxtrust/action/UpdateScopeAction.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/ScopeService.java
  server/src/main/webapp/resources/ox/selectSelectableEntityDialog.xhtml
Labels: enhancement

#1401 Reorder oxTrust log level #1400
  server/src/main/java/org/gluu/oxtrust/action/UpdateGroupAction.java
  static/src/main/resources/META-INF/resources/schema/oxauth-config.xml.json
  static/src/main/resources/META-INF/resources/schema/oxtrust.properties.json
Labels: enhancement

#1404 Error in oxtrust logs on creating new TR #1403
  server/src/main/java/org/gluu/oxtrust/ldap/service/TemplateService.java
Labels: bug

#1406 Update existing scope show error #1405
  server/src/main/java/org/gluu/oxtrust/action/UpdateScopeAction.java
Labels: bug

#1414 Improve layout and element design #1093
  server/src/main/webapp/WEB-INF/incl/authentication/customAuthenticationForm.xhtml
  server/src/main/webapp/WEB-INF/incl/organization/cacheRefreshForm.xhtml
  server/src/main/webapp/WEB-INF/incl/organization/organizationForm.xhtml
  server/src/main/webapp/resources/ox/ldapConfig.xhtml
  server/src/main/webapp/resources/ox/simplePropertiesList.xhtml
Labels: enhancement

#1415 Authentication graph improvement #1196
  server/src/main/resources/oxtrust.properties
  server/src/main/resources/oxtrust_en.properties
  server/src/main/resources/oxtrust_fr.properties
  server/src/main/webapp/resources/js/dashboard.js
Labels: enhancement

#1416 Improve some public facing pages to match Gluu design #1264
  server/src/main/webapp/conversation_error.xhtml
  server/src/main/webapp/error.xhtml
  server/src/main/webapp/error_service.xhtml
Labels: enhancement

#1419 Oops when uploading ldif #1387
  server/src/main/java/org/gluu/oxtrust/action/AttributeImportAction.java
Labels: bug

#1420 Add more space between elements in Certificates view #1417
  server/src/main/webapp/configuration/certificateManagement.xhtml
Labels: enhancement

#1422 Configuration > Certificates enhancements #1328
  server/src/main/java/org/gluu/oxtrust/action/CertificateManagementAction.java
Labels: enhancement

#1427 Typo in oxtrust.properties #1374
  server/src/main/resources/oxtrust.properties
  server/src/main/resources/oxtrust_en.properties
  server/src/main/resources/oxtrust_fr.properties
  server/src/main/resources/oxtrust_ru.properties
  server/src/main/webapp/WEB-INF/incl/person/personForm.xhtml
  server/src/main/webapp/attribute/addAttribute.xhtml
  server/src/main/webapp/attribute/attributeInventory.xhtml
Labels: enhancement

#1430 Make client form work with tabulation #1262
  server/src/main/webapp/WEB-INF/incl/client/clientForm.xhtml
Labels: enhancement

#1431 Password length validation not working #1428
  server/src/main/java/org/gluu/oxtrust/action/UpdatePersonAction.java
Labels: bug

#1432 Improve registration confirmation page #1425
  server/src/main/resources/oxtrust.properties
  server/src/main/resources/oxtrust_en.properties
  server/src/main/resources/oxtrust_fr.properties
  server/src/main/webapp/confirm/registration.xhtml
Labels: enhancement

#1436 conversation_error, 30 mins of inactivity #1029
  server/src/main/java/org/gluu/oxtrust/action/ConfigureCacheRefreshAction.java
  server/src/main/webapp/WEB-INF/incl/organization/cacheRefreshForm.xhtml
  server/src/main/webapp/organization/updateOrganization.xhtml
Labels: enhancement

#1437 Register page pop-up displayed for another user #1269
  server/src/main/java/org/gluu/oxtrust/action/RegisterPersonAction.java
Labels: enhancement

#1439 Add ability to download a certificate from the list of cert #1421
  server/src/main/java/org/gluu/oxtrust/action/AttributeInventoryAction.java
  server/src/main/java/org/gluu/oxtrust/action/CertificateManagementAction.java
  server/src/main/java/org/gluu/oxtrust/util/X509CertificateShortInfo.java
  server/src/main/webapp/configuration/certificateManagement.xhtml
Labels: enhancement

#1443 Update of TR leads to Oops page #1440
  server/src/main/java/org/gluu/oxtrust/action/UpdateTrustRelationshipAction.java
  server/src/main/webapp/WEB-INF/incl/trustmanager/trustRelationshipForm.xhtml
Labels: bug

#1444 Regex validation of attribute leads to Error Page #1434
  server/src/main/java/org/gluu/oxtrust/action/UpdateAttributeAction.java
Labels: bug
