Repository GluuFederation/oxTrust, pull requests merged in 2019-06, with the labels that each got.

#1676 Ox trust/issues/1672
  server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java
  server/src/main/java/org/gluu/oxtrust/action/uma/UmaScopeDownloadAction.java
  server/src/main/java/org/gluu/oxtrust/action/uma/UpdateUmaScopeAction.java
  server/src/main/resources/META-INF/navigation/addUmaScope.navigation.xml
  server/src/main/resources/META-INF/navigation/updateUmaScope.navigation.xml
  server/src/main/webapp/resources/ox/acceptRemovalDialog.xhtml
  server/src/main/webapp/uma/scope.xhtml
  server/src/main/webapp/uma/scope/addUmaScope.xhtml
  server/src/main/webapp/uma/scope/updateUmaScope.xhtml
Labels: enhancement

#1677 No confirmation message on profile password change #1667
  server/src/main/java/org/gluu/oxtrust/action/PasswordValidationAction.java
  server/src/main/webapp/profile/person/viewProfile.xhtml
  server/src/main/webapp/resources/ox/changePasswordDialog.xhtml
Labels: enhancement

#1678 Calendar popup for Date type attributes #1612
  server/src/main/java/org/gluu/oxtrust/action/UpdatePersonAction.java
  server/src/main/webapp/WEB-INF/incl/person/userForm.xhtml
  server/src/main/webapp/person/addPerson.xhtml
Labels: enhancement

#1680 Unable to add/update attribute when data source is couchbase #1679
  server/src/main/java/org/gluu/oxtrust/action/UpdateAttributeAction.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/ClientService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/DataSourceTypeService.java
Labels: enhancement

#1681 Added oxTrust API Code For Gluu Radius
  .gitignore
  api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/radius/GluuRadiusClientWebResource.java
  api-server/src/main/java/org/gluu/oxtrust/api/server/api/impl/radius/GluuRadiusConfigWebResource.java
  api-server/src/main/java/org/gluu/oxtrust/api/server/util/ApiConstants.java
  pom.xml
  server/pom.xml
  server/src/main/java/org/gluu/oxtrust/action/ProductInstallationCheckerAction.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/radius/GluuRadiusClientService.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/radius/GluuRadiusConfigService.java
  server/src/main/java/org/gluu/oxtrust/util/ProductInstallationChecker.java
Labels: enhancement

#1685 Added scope info is not shown in Client config Summary #1684
  server/src/main/java/org/gluu/oxtrust/action/UpdateClientAction.java
  server/src/main/webapp/resources/ox/clientSummary.xhtml
Labels: exclude from release notes

#1691 Scopes list not properly loaded in idp-initiated flows config form #1690
  server/src/main/java/org/gluu/oxtrust/action/PassportIdpInitiatedAction.java
Labels: enhancement, exclude from release notes

#1692 Replace hostname placeholder with actual server name #1689
  server/src/main/java/org/gluu/oxtrust/action/PassportIdpInitiatedAction.java
Labels: enhancement, exclude from release notes

#1694 Support additional OIDC params in idp-initiated passport form #1688
  server/src/main/java/org/gluu/oxtrust/action/PassportIdpInitiatedAction.java
  server/src/main/java/org/gluu/oxtrust/ldap/service/OrganizationService.java
  server/src/main/webapp/passport/idpInitiatedFlows.xhtml
  server/src/main/webapp/resources/ox/simpleMapProperties.xhtml
Labels: enhancement

#1699 OpenID Scopes Display Name is empty #1698
  server/src/main/webapp/WEB-INF/incl/layout/leftmenu.xhtml
  server/src/main/webapp/WEB-INF/incl/scope/scopeForm.xhtml
Labels: bug, exclude from release notes

#1703 Bug: Failed to add policy script in UMA scope #1702
  server/src/main/webapp/resources/ox/selectSelectableEntityDialog.xhtml
  server/src/main/webapp/uma/scope/updateUmaScope.xhtml
Labels: bug, exclude from release notes
